// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID             int32              `db:"id" json:"id"`
	UserID         string             `db:"user_id" json:"user_id"`
	BasicID        string             `db:"basic_id" json:"basic_id"`
	ChatMode       string             `db:"chat_mode" json:"chat_mode"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	MarkAsReadMode string             `db:"mark_as_read_mode" json:"mark_as_read_mode"`
	PictureUrl     *string            `db:"picture_url" json:"picture_url"`
	PremiumID      *string            `db:"premium_id" json:"premium_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BotFollower struct {
	ID         int32              `db:"id" json:"id"`
	BotID      int32              `db:"bot_id" json:"bot_id"`
	UserID     int32              `db:"user_id" json:"user_id"`
	FollowedAt pgtype.Timestamptz `db:"followed_at" json:"followed_at"`
}

type Message struct {
	ID            int32              `db:"id" json:"id"`
	BotID         int32              `db:"bot_id" json:"bot_id"`
	MessageType   string             `db:"message_type" json:"message_type"`
	RecipientType *string            `db:"recipient_type" json:"recipient_type"`
	RecipientID   *string            `db:"recipient_id" json:"recipient_id"`
	Content       []byte             `db:"content" json:"content"`
	RetryKey      pgtype.UUID        `db:"retry_key" json:"retry_key"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID            int32              `db:"id" json:"id"`
	UserID        string             `db:"user_id" json:"user_id"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	PictureUrl    *string            `db:"picture_url" json:"picture_url"`
	StatusMessage *string            `db:"status_message" json:"status_message"`
	Language      *string            `db:"language" json:"language"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Webhook struct {
	ID        int32              `db:"id" json:"id"`
	BotID     int32              `db:"bot_id" json:"bot_id"`
	Endpoint  string             `db:"endpoint" json:"endpoint"`
	Active    bool               `db:"active" json:"active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
