// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error)
	DeleteBot(ctx context.Context, userID string) error
	GetBot(ctx context.Context, id int32) (Bot, error)
	GetBotByBasicID(ctx context.Context, basicID string) (Bot, error)
	GetBotByUserID(ctx context.Context, userID string) (Bot, error)
	ListBots(ctx context.Context) ([]Bot, error)
	UpdateBot(ctx context.Context, arg UpdateBotParams) (Bot, error)
}

var _ Querier = (*Queries)(nil)
